### ISSUE TITLE
NotImplementedError Invalid magic

### ISSUE THREAD

**Issue by Gooberpatrol66** [mgorny/eclean-kernel#11]
root@gentooserver /media/store/Data/VM/gnu-hurd/cross-hurd-smp # ls /boot
EFI                                     System.map-5.3.12-gentoo-x86_64      vmlinuz-5.4.28-gentoo-x86_64
grub                                    System.map-5.3.12-gentoo-x86_64.old  vmlinuz-5.4.28-gentoo-x86_64.old
initramfs-5.3.12-gentoo-x86_64.img      System.map-5.4.28-gentoo-x86_64      vmlinuz-5.4.38-gentoo-x86_64
initramfs-5.3.12-gentoo-x86_64.img.old  System.map-5.4.28-gentoo-x86_64.old  vmlinuz-5.4.38-gentoo-x86_64.old
initramfs-5.4.28-gentoo-x86_64.img      System.map-5.4.38-gentoo-x86_64      vmlinuz-5.4.48-gentoo-x86_64
initramfs-5.4.28-gentoo-x86_64.img.old  System.map-5.4.38-gentoo-x86_64.old  vmlinuz-5.4.48-gentoo-x86_64.old
initramfs-5.4.38-gentoo-x86_64.img      System.map-5.4.48-gentoo-x86_64      vmlinuz-5.4.60-gentoo-x86_64
initramfs-5.4.38-gentoo-x86_64.img.old  System.map-5.4.48-gentoo-x86_64.old  vmlinuz-5.4.60-gentoo-x86_64.old
initramfs-5.4.48-gentoo-x86_64.img      System.map-5.4.60-gentoo-x86_64      vmlinuz-5.4.66-gentoo-x86_64
initramfs-5.4.48-gentoo-x86_64.img.old  System.map-5.4.60-gentoo-x86_64.old  vmlinuz-5.4.66-gentoo-x86_64.old
initramfs-5.4.60-gentoo-x86_64.img      vmlinuz-5.3.12-gentoo-x86_64
initramfs-5.4.60-gentoo-x86_64.img.old  vmlinuz-5.3.12-gentoo-x86_64.old
root@gentooserver /media/store/Data/VM/gnu-hurd/cross-hurd-smp # eclean-kernel --debug -dn 2
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/eclean-kernel", line 26, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.7/site-packages/ecleankernel/cli.py", line 156, in main
    kernels = find_kernels(exclusions=exclusions)
  File "/usr/lib/python3.7/site-packages/ecleankernel/kernel.py", line 275, in find_kernels
    realkv = newk.real_kv
  File "/usr/lib/python3.7/site-packages/ecleankernel/kernel.py", line 156, in real_kv
    + ' %s (!= HdrS)' % vmlinuz)
NotImplementedError: Invalid magic for kernel file /boot/vmlinuz-5.4.66-gentoo-x86_64 (!= HdrS)
root@gentooserver /media/store/Data/VM/gnu-hurd/cross-hurd-smp # eclean-kernel --list-kernels
eclean-kernel has met the following issue:

  NotImplementedError('Invalid magic for kernel file /boot/vmlinuz-5.4.66-gentoo-x86_64 (!= HdrS)')

If you believe that the mentioned issue is a bug, please report it
to https://github.com/mgorny/eclean-kernel/issues. If possible,
please attach the output of 'eclean-kernel --list-kernels' and your
regular eclean-kernel call with additional '--debug' argument.

**Comment by Jannik2099** [comment]
> cross-hurd-smp

Is this a hurd kernel? If so, I assume hurd does not have a bzImage header / stub?

Could you try again with a fresh master now that #10 is merged, I wonder if it helps here

**Comment by Gooberpatrol66** [comment]
Sorry, this is Linux, not Hurd. I just happened to be in that directory because I was doing some work on it.

**Comment by ironiridis** [comment]
@Gooberpatrol66 Did you ever get a change to try this again?
