### ISSUE TITLE
/boot no longer automatically mounted

### ISSUE THREAD

**Issue by tastytea** [mgorny/eclean-kernel#19]
Version: 2.99.2

When `/boot` isn't mounted, I get this error message:

> eclean-kernel has met the following issue:
>
>   SystemError('No vmlinuz found. This seems ridiculous, aborting.')

When `/boot` is mounted, it works. It automatically mounted with 0.4.3. `eclean-kernel --help` lists the `--no-mount` option, which indicates that it should automatically mount by default.

**Debug output:**

``` shellsession
$ sudo eclean-kernel --list-kernels
5.10.49-gentoo-r1-x86_64 [None]
- modules: /lib/modules/5.10.49-gentoo-r1-x86_64
- build: /usr/src/linux-5.10.49-gentoo-r1
- last modified: 2021-07-17 11:58:31
$ sudo eclean-kernel -n 2 --destructive --debug
DEBUG:root:Layout failed: <class 'ecleankernel.layout.blspec.BlSpecLayout'>; exception: /boot/[EFI/]918b823714be1082a7eebebf5ac4ea54 not found
DEBUG:root:Layout: <ecleankernel.layout.std.StdLayout object at 0x7f5e22b7bb50>
DEBUG:root:Bootloader failed: <class 'ecleankernel.bootloader.lilo.LILO'>
DEBUG:root:Bootloader failed: <class 'ecleankernel.bootloader.grub2.GRUB2'>
DEBUG:root:Bootloader failed: <class 'ecleankernel.bootloader.grub.GRUB'>
DEBUG:root:Bootloader failed: <class 'ecleankernel.bootloader.yaboot.Yaboot'>
DEBUG:root:Bootloader: <ecleankernel.bootloader.symlinks.Symlinks object at 0x7f5e22b7bb20>
DEBUG:root:Sorter: <ecleankernel.sort.VersionSort object at 0x7f5e22b7bbb0>
DEBUG:root:in get_removal_list()
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/eclean-kernel", line 33, in <module>
    sys.exit(load_entry_point('eclean-kernel==2.99.2', 'console_scripts', 'eclean-kernel')())
  File "/usr/lib/python3.9/site-packages/ecleankernel/__main__.py", line 382, in setuptools_main
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/python3.9/site-packages/ecleankernel/__main__.py", line 242, in main
    removals = get_removal_list(
  File "/usr/lib/python3.9/site-packages/ecleankernel/process.py", line 83, in get_removal_list
    raise SystemError(
SystemError: No vmlinuz found. This seems ridiculous, aborting.
```

**Comment by mgorny** [comment]
This is probably #17. I'm sorry, I have neglected this project a lot. I'd like to finish #12 and then make a new release.

**Comment by tastytea** [comment]
Yes, it works with the patch. Thank you!
